# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  core-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/CoreTests
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: CoreTests
      run: dotnet test --no-build --verbosity normal
  dispatcher-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/DefaultTransportTests
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: DefaultDispatcherTests
      run: dotnet test --filter "FullyQualifiedName~DefaultDispatcherTests" --no-build --verbosity normal
    - name: PacketAggregatorTests
      run: dotnet test --filter "FullyQualifiedName~PacketAggregatorTests" --no-build --verbosity normal
